### ISSUE TITLE
Add the ability to format to devshell (and/or documenting it)

### ISSUE THREAD

**Issue by Ben-PH** [a-kenji/nix-uri#141]
I find myself using `nix shell nixpkgs#rustfmt -c cargo fmt` to format my code base. Either it's missing from the project config, or it's there, but there's a different way to do it that I'm not aware.

**Comment by a-kenji** [comment]
Yes, there is a different way, I will document it in `CONTRIBUTING.md`, basically there are two ways:

```
treefmt # in the devshell
```
or 
```
nix fmt
```

**Comment by a-kenji** [comment]
Closed through:  #170
