### ISSUE TITLE
Parse file type correctly

### ISSUE THREAD

**Issue by a-kenji** [a-kenji/nix-uri#54]
This should be parsed correctly:
```
file:///home/lucas/Documents/École/test
```

This is the current output:
```
There was an error parsing the uri: file:///home/lucas/Documents/École/test
Error: The type is not known: file
```

**Comment by Ben-PH** [comment]
https://github.com/a-kenji/nix-uri/blob/a77f4ac4d80baf1409bbba745883c50ba4ef2376/src/flakeref.rs#L125-L141
